# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IPUytkMVMmi0t-eO2DV4QNCk3Kc3bCqO
"""

from flask import Flask
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

api = Flask(__name__)

# Tudo que eu escrever aqui vai rodar quando eu inicializar a api
# Lendo dados
dados = pd.read_csv("https://raw.githubusercontent.com/lorranmendes22/regressao-linear/main/casas%20-%20casas.csv")

# Separar as features - (x) e classes/variável-alvo (0,1) - (y)
x = dados[['tamanho']] # DataFrame por isso passo uma lista de colunas do que eu quero
y = dados['preco'] # Array

# Separar treino e teste
SEED = 42
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=SEED)

# Criar o modelo
modelo = LinearRegression()
modelo.fit(x_train, y_train)

# Imprimir os coeficientes y = ax + b
# x - tamanho
# a - coeficiente de inclinação da reta
# b - deslocamento da reta no eixo y
print(f"y = {modelo.coef_[0]}x + {modelo.intercept_}")

@api.route("/preco/<int:tamanho>") # Get
def calcula_preco(tamanho):
    result = modelo.predict([[tamanho]])
    return f"O preço da casa é: {result[0]}"

@api.route("/preco-avancado/<int:tamanho>") # Get
def calcula_preco_avancado(tamanho):
    result = modelo.predict([[tamanho]])
    return f"O preço da casa é: {result[0]}"

if __name__ == "__main__":
    api.run(debug=True)

